"""Regression gate: hashes of existing v3 presets must not drift.

This test is the main backward-compatibility guard for the A0-C phases
of the ferro-micro integration plan. Every preset in ``presets_v3/`` is
generated at a small resolution with a fixed seed; the SHA-256 of the
resulting grayscale image is compared against a stored baseline.

If a change to any module *intentionally* alters the pixels for an
existing preset, the baseline file must be regenerated by running::

    python -m tests.test_v3_presets_snapshot_baseline --regenerate

The regeneration helper is guarded behind ``if __name__ == "__main__"``
so the pytest run never rewrites it accidentally.
"""

from __future__ import annotations

import hashlib
import json
import unittest
from pathlib import Path

from core.metallography_v3.pipeline_v3 import MetallographyPipelineV3

REPO_ROOT = Path(__file__).resolve().parents[1]
BASELINE_PATH = REPO_ROOT / "tests" / "fixtures" / "presets_baseline_hashes.json"
PRESETS_DIR = REPO_ROOT / "presets_v3"
PROFILES_DIR = REPO_ROOT / "profiles_v3"

_RENDER_RESOLUTION = (128, 128)
_RENDER_SEED = 42


def _load_baseline() -> dict:
    if not BASELINE_PATH.exists():
        raise FileNotFoundError(
            f"Baseline snapshot not found: {BASELINE_PATH}. "
            "Run 'python -m tests.test_v3_presets_snapshot_baseline --regenerate' first."
        )
    return json.loads(BASELINE_PATH.read_text(encoding="utf-8"))


def _render_preset(pipeline: MetallographyPipelineV3, name: str) -> dict:
    payload = pipeline.load_preset(name)
    payload["resolution"] = list(_RENDER_RESOLUTION)
    payload["seed"] = _RENDER_SEED
    request = pipeline.request_from_preset(payload)
    result = pipeline.generate(request)
    image_gray = result.image_gray
    return {
        "sha256_gray": hashlib.sha256(image_gray.tobytes()).hexdigest(),
        "shape": list(image_gray.shape),
        "mean": float(image_gray.mean()),
        "std": float(image_gray.std()),
    }


class PresetSnapshotBaselineTest(unittest.TestCase):
    """Ensures that no phase silently changes the grayscale pixels of
    an existing preset without updating the baseline file."""

    @classmethod
    def setUpClass(cls) -> None:
        cls.baseline = _load_baseline()
        cls.pipeline = MetallographyPipelineV3(
            presets_dir=PRESETS_DIR,
            profiles_dir=PROFILES_DIR,
        )

    def test_all_presets_unchanged(self) -> None:
        expected = self.baseline["presets"]
        preset_paths = self.pipeline.list_preset_paths()
        # Only check presets that existed when the baseline was created.
        # New presets (added during ferro-micro integration) are ignored here.
        drifted: list[str] = []
        for path in preset_paths:
            name = path.stem
            if name not in expected:
                continue
            actual = _render_preset(self.pipeline, name)
            if actual["sha256_gray"] != expected[name]["sha256_gray"]:
                drifted.append(
                    f"{name}: expected hash {expected[name]['sha256_gray'][:12]}"
                    f" (mean {expected[name]['mean']:.1f})"
                    f" → got {actual['sha256_gray'][:12]}"
                    f" (mean {actual['mean']:.1f})"
                )
        if drifted:
            self.fail(
                "The following presets produce different grayscale output than the baseline. "
                "Either revert the change or regenerate the baseline intentionally:\n"
                + "\n".join(drifted)
            )

    def test_baseline_covers_all_existing_presets(self) -> None:
        """Signals when someone adds a new preset without updating the baseline."""
        expected_names = set(self.baseline["presets"].keys())
        actual_names = {p.stem for p in self.pipeline.list_preset_paths()}
        missing_in_baseline = actual_names - expected_names
        if missing_in_baseline:
            self.skipTest(
                "New presets not covered by baseline (expected during ferro-micro integration): "
                + ", ".join(sorted(missing_in_baseline))
            )


def regenerate_baseline() -> None:
    """Overwrite ``presets_baseline_hashes.json`` with the current renders.

    Use this only after an intentional change that must update the baseline.
    """
    pipeline = MetallographyPipelineV3(
        presets_dir=PRESETS_DIR,
        profiles_dir=PROFILES_DIR,
    )
    hashes: dict = {}
    errors: dict = {}
    for path in pipeline.list_preset_paths():
        name = path.stem
        try:
            hashes[name] = _render_preset(pipeline, name)
        except Exception as exc:  # pragma: no cover - helper only
            errors[name] = f"{type(exc).__name__}: {exc}"
    payload = {
        "generated_at_note": "Baseline for A0.3 regression gate. Do not regenerate unless intentional changes expected.",
        "resolution": list(_RENDER_RESOLUTION),
        "seed": _RENDER_SEED,
        "presets": hashes,
        "errors": errors,
    }
    BASELINE_PATH.parent.mkdir(parents=True, exist_ok=True)
    BASELINE_PATH.write_text(
        json.dumps(payload, indent=2, sort_keys=True, ensure_ascii=False),
        encoding="utf-8",
    )
    print(f"Regenerated baseline with {len(hashes)} presets ({len(errors)} errors)")


if __name__ == "__main__":
    import sys

    if "--regenerate" in sys.argv:
        regenerate_baseline()
    else:
        unittest.main()
